<a href="https://colab.research.google.com/github/vanamaabhi2004/ML-AI/blob/main/Feb_6_Intro_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.datasets import load_diabetes
dataset  = load_diabetes()
X = dataset.data
Y = dataset.target

In [ ]:
# Using only bmi as the input
# Univariate Single-output regression task
inp = X[:,2].reshape(-1,1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inp, Y, test_size = 0.3, random_state = 1)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors = 2, metric = 'euclidean', weights = 'uniform')
knn.fit(x_train, y_train)

KNeighborsRegressor(metric='euclidean', n_neighbors=2)

In [ ]:
# Crossvalidation

Dataset--> 442

10 times (folds)
P1, P2, ........P10

k-fold cross-validation

                Fold 1
      test -->   P1
    train -->    Everything else


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits = 10)
knn = KNeighborsRegressor(n_neighbors = 2, metric = 'euclidean', weights = 'uniform')
cross_val_score(knn, inp, Y, cv = kf, scoring = 'neg_mean_squared_error')

array([-5219.01111111, -4806.87777778, -5755.17613636, -7091.73295455,
       -5268.0625    , -5442.69886364, -6908.875     , -4876.54545455,
       -7353.85795455, -4307.76136364])

In [ ]:
cross_val_score(knn, inp, Y, cv = kf, scoring = 'neg_mean_squared_error').mean()

-5703.059911616163

In [ ]:
knn = KNeighborsRegressor(n_neighbors = 1, metric = 'euclidean', weights = 'uniform')
cross_val_score(knn, inp, Y, cv = kf, scoring = 'neg_mean_squared_error').mean()

-7320.253383838384

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits = 10)
cvs = []
c = 0

for k in range(1, 31):# n_neighbors
    for met in ['manhattan', 'euclidean']:
        for typ in ['uniform','distance']:
            knn = KNeighborsRegressor(n_neighbors = k, metric = met, weights = typ)
            cvs.append(cross_val_score(knn, inp, Y, cv = kf, scoring = 'neg_mean_squared_error').mean())
            print(c, ' (', k,', ' ,met,', ', typ, ') --> ', cvs[c], sep = '')
            c = c + 1

0 (1, manhattan, uniform) --> -7320.253383838384
1 (1, manhattan, distance) --> -7320.253383838384
2 (1, euclidean, uniform) --> -7320.253383838384
3 (1, euclidean, distance) --> -7320.253383838384
4 (2, manhattan, uniform) --> -5703.059911616163
5 (2, manhattan, distance) --> -6025.151439122315
6 (2, euclidean, uniform) --> -5703.059911616163
7 (2, euclidean, distance) --> -6025.151439122315
8 (3, manhattan, uniform) --> -4986.769264870932
9 (3, manhattan, distance) --> -5482.234969415985
10 (3, euclidean, uniform) --> -4986.769264870932
11 (3, euclidean, distance) --> -5482.234969415985
12 (4, manhattan, uniform) --> -4709.201944444445
13 (4, manhattan, distance) --> -5300.528706884778
14 (4, euclidean, uniform) --> -4709.201944444445
15 (4, euclidean, distance) --> -5300.528706884778
16 (5, manhattan, uniform) --> -4517.772365656565
17 (5, manhattan, distance) --> -5278.9742351631885
18 (5, euclidean, uniform) --> -4517.772365656565
19 (5, euclidean, distance) --> -5278.974235163188

In [ ]:
max(cvs)

-3973.8861598841636

In [ ]:
cvs.index(max(cvs))

104

In [ ]:
from sklearn.model_selection import GridSearchCV, KFold
kf = KFold(n_splits = 10)
model = KNeighborsRegressor()
hyper_params = {'n_neighbors':range(1,31),
                'metric':['manhattan','euclidean'],
                'weights':['uniform', 'distance']
               }

gcv = GridSearchCV(model, param_grid = hyper_params, cv = kf, scoring = 'neg_mean_squared_error')
gcv.fit(inp, Y)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             estimator=KNeighborsRegressor(),
             param_grid={'metric': ['manhattan', 'euclidean'],
                         'n_neighbors': range(1, 31),
                         'weights': ['uniform', 'distance']},
             scoring='neg_mean_squared_error')

In [ ]:
gcv.best_params_

{'metric': 'manhattan', 'n_neighbors': 27, 'weights': 'uniform'}

In [ ]:
gcv.best_score_

-3973.8861598841636

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, KFold
kf = KFold(n_splits = 10)
model = KNeighborsRegressor()
hyper_params = {'n_neighbors':range(1,31),
                'metric':['manhattan','euclidean'],
                'weights':['uniform', 'distance']
               }

rcv = RandomizedSearchCV(model, param_distributions = hyper_params, cv = kf, scoring = 'neg_mean_squared_error')
rcv.fit(inp, Y)
rcv.best_params_

{'weights': 'uniform', 'n_neighbors': 22, 'metric': 'euclidean'}

In [ ]:
rcv.best_score_

-3981.6971389514983

In [ ]:
data = np.array([1,2,3,4,5])

# Standardization
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(data.reshape(-1,1))

StandardScaler()

In [ ]:
ss.transform(data.reshape(-1,1))

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [ ]:
# Normalization
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler(feature_range = (-5,5))
mm.fit(data.reshape(-1,1))
mm.transform(data.reshape(-1,1))

array([[-5. ],
       [-2.5],
       [ 0. ],
       [ 2.5],
       [ 5. ]])

In [ ]:
from sklearn.datasets import load_diabetes
dataset  = load_diabetes()
X = dataset.data
Y = dataset.target

from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
mysteps = [('mm', MinMaxScaler()), ('knn', KNeighborsRegressor())]

mpipe = Pipeline(steps = mysteps)

from sklearn.model_selection import GridSearchCV, KFold
kf = KFold(n_splits = 10)

hyper_params = {'knn__n_neighbors':range(1,31),
                'knn__metric':['manhattan','euclidean'],
                'knn__weights':['uniform', 'distance']
               }

gcv = GridSearchCV(mpipe, param_grid = hyper_params, cv = kf, scoring = 'neg_mean_squared_error')
gcv.fit(X, Y)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=False),
             estimator=Pipeline(steps=[('mm', MinMaxScaler()),
                                       ('knn', KNeighborsRegressor())]),
             param_grid={'knn__metric': ['manhattan', 'euclidean'],
                         'knn__n_neighbors': range(1, 31),
                         'knn__weights': ['uniform', 'distance']},
             scoring='neg_mean_squared_error')

In [ ]:
gcv.best_score_

-3253.0680964703456

In [ ]:
gcv.best_params_

{'knn__metric': 'euclidean',
 'knn__n_neighbors': 27,
 'knn__weights': 'distance'}

In [ ]:
gcv.best_estimator_

Pipeline(steps=[('mm', MinMaxScaler()),
                ('knn',
                 KNeighborsRegressor(metric='euclidean', n_neighbors=27,
                                     weights='distance'))])